package com.google.adk.finance.v11;

import com.google.adk.finance.v11.hooks.HookPolicy;
import com.google.adk.finance.v11.hooks.HookRegistry;
import com.google.adk.finance.v11.hooks.HookResult;
import com.google.adk.finance.v11.hooks.ResponseValidationHook;
import com.google.adk.models.LlmResponse;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

class ResponseValidationHookTest {

    private ResponseValidationHook hook;
    private HookRegistry hookRegistry;

    @BeforeEach
    void setUp() {
        hookRegistry = new HookRegistry();
        hook = new ResponseValidationHook(hookRegistry);
    }

    @Test
    @DisplayName("Should detect blank response and return safe error fallback with disclaimer")
    void shouldDetectBlankResponse() {
        Content blankContent = Content.builder().role("model").parts(List.of(Part.fromText("   "))).build();
        LlmResponse blankResponse = LlmResponse.builder().content(blankContent).build();

        Optional<LlmResponse> result = hook.call(null, blankResponse);

        assertThat(result).isPresent();
        String text = extractText(result.get());
        assertThat(text).contains("Error: Generated response was blank.");
        assertThat(text).contains("Regulatory Notice & Disclaimer");
        assertThat(hookRegistry.getBlockedCount()).isEqualTo(1);
    }

    @Test
    @DisplayName("Should append regulatory disclaimer when missing from model response")
    void shouldAppendRegulatoryDisclaimerWhenMissing() {
        Content content = Content.builder()
                .role("model")
                .parts(List.of(Part.fromText("Infosys reported 4.5% YoY revenue growth in Q3.")))
                .build();
        LlmResponse response = LlmResponse.builder().content(content).build();

        Optional<LlmResponse> result = hook.call(null, response);

        assertThat(result).isPresent();
        String text = extractText(result.get());
        assertThat(text).contains("Infosys reported 4.5% YoY revenue growth in Q3.");
        assertThat(text).contains("Regulatory Notice & Disclaimer (v11)");
        assertThat(text).contains("licensed fiduciary");
    }

    @Test
    @DisplayName("Should append source context note if external data tools were invoked but citations missing")
    void shouldAppendSourceContextWhenToolsInvoked() {
        // Record tool invocations in registry
        hookRegistry.recordToolInvocation("get_stock_info");
        hookRegistry.recordToolInvocation("google_search");

        Content content = Content.builder()
                .role("model")
                .parts(List.of(Part.fromText("TCS is trading at 3900 INR with a stable forward multiple. " +
                        "Regulatory Notice & Disclaimer: Not financial advice.")))
                .build();
        LlmResponse response = LlmResponse.builder().content(content).build();

        Optional<LlmResponse> result = hook.call(null, response);

        assertThat(result).isPresent();
        String text = extractText(result.get());
        assertThat(text).contains("Source Context (v11)");
        assertThat(text).contains("Yahoo Finance MCP and/or Google Search");
    }

    @Test
    @DisplayName("Should leave clean conformant response unmodified")
    void shouldLeaveConformantResponseUnmodified() {
        String cleanReport = """
                Executive Thesis: Infosys shows resilient earnings.
                
                Source: Yahoo Finance MCP data indicates P/E of 28.5.
                
                ---
                > **Regulatory Notice & Disclaimer (v11)**: This analysis is generated by an autonomous AI system
                for educational and decision-support research purposes only. It does not constitute certified financial,
                legal, or investment advice. Always consult a licensed fiduciary before executing financial transactions.
                """;

        Content content = Content.builder()
                .role("model")
                .parts(List.of(Part.fromText(cleanReport)))
                .build();
        LlmResponse response = LlmResponse.builder().content(content).build();

        Optional<LlmResponse> result = hook.call(null, response);

        assertThat(result).isEmpty(); // Unmodified
        assertThat(hookRegistry.getSuccessCount()).isEqualTo(1);
    }

    @Test
    @DisplayName("Should pass through function call response without treating as blank response")
    void shouldPassThroughFunctionCallResponse() {
        com.google.genai.types.FunctionCall fnCall = com.google.genai.types.FunctionCall.builder()
                .name("get_stock_info")
                .args(java.util.Map.of("symbol", "INFY.NS"))
                .build();
        Part part = Part.builder().functionCall(fnCall).build();
        Content content = Content.builder().role("model").parts(List.of(part)).build();
        LlmResponse response = LlmResponse.builder().content(content).build();

        Optional<LlmResponse> result = hook.call(null, response);

        assertThat(result).isEmpty(); // Must NOT be modified or replaced with error fallback
        assertThat(hookRegistry.getBlockedCount()).isEqualTo(0);
    }

    private String extractText(LlmResponse response) {
        if (response.content().isEmpty()) return "";
        Content c = response.content().get();
        StringBuilder sb = new StringBuilder();
        for (Part p : c.parts().orElse(List.of())) {
            p.text().ifPresent(sb::append);
        }
        return sb.toString();
    }
}
