package com.google.adk.finance.v8.guardrails.output;

import com.google.adk.finance.v8.guardrails.GuardrailResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Deterministic model output guardrail detecting offensive, abusive, derogatory, or toxic language.
 * <p>
 * Ensures institutional professionalism by intercepting model-generated responses before delivery
 * to the end user. When offensive content is detected, the guardrail blocks delivery and substitutes
 * a deterministic, safe response.
 */
public class OffensiveLanguageDetector {
    private static final Logger logger = LoggerFactory.getLogger(OffensiveLanguageDetector.class);

    public static final String SAFE_FALLBACK_RESPONSE =
            "I apologize, but I cannot provide that response as it violates our professional communication policy " +
            "regarding appropriate, constructive language. Please let me know how else I can assist with your portfolio analysis.";

    public record OffensiveMatch(String term, String category, int start, int end) {}

    // Configurable offensive patterns covering explicit profanity, insults, harassment, and discriminatory slurs
    private static final List<Pattern> OFFENSIVE_PATTERNS = List.of(
            // Profanities & Vulgarities
            Pattern.compile("\\b(?:fuck|shit|bitch|bastard|asshole|cunt|dick|piss)\\b", Pattern.CASE_INSENSITIVE),
            // Abusive Insults & Harassment
            Pattern.compile("\\b(?:idiot|moron|stupid\\s+scum|retard|kill\\s+yourself|shut\\s+the\\s+fuck\\s+up)\\b", Pattern.CASE_INSENSITIVE),
            // Hate speech & slurs
            Pattern.compile("\\b(?:nigger|faggot|chink|spic|kike|slut|whore)\\b", Pattern.CASE_INSENSITIVE)
    );

    public OffensiveLanguageDetector() {}

    /**
     * Inspects output text for offensive or abusive terms.
     *
     * @param text output text generated by the model
     * @return list of detected {@link OffensiveMatch} instances
     */
    public List<OffensiveMatch> detect(String text) {
        if (text == null || text.isBlank()) {
            return Collections.emptyList();
        }

        List<OffensiveMatch> matches = new ArrayList<>();
        for (Pattern pattern : OFFENSIVE_PATTERNS) {
            Matcher m = pattern.matcher(text);
            while (m.find()) {
                matches.add(new OffensiveMatch(m.group(), "PROFANITY_OR_ABUSE", m.start(), m.end()));
            }
        }
        return matches;
    }

    /**
     * Evaluates output text against offensive language standards.
     *
     * @param text the candidate model response
     * @return {@link GuardrailResult#allow} if clean, or {@link GuardrailResult#block} with safe fallback if violated
     */
    public GuardrailResult evaluate(String text) {
        List<OffensiveMatch> matches = detect(text);
        if (matches.isEmpty()) {
            return GuardrailResult.allow("OffensiveLanguageDetector", "Output passed language policy check.");
        }

        logger.warn("[Output Guardrail] Blocked response containing {} offensive/abusive term(s).", matches.size());
        return GuardrailResult.block(
                "OffensiveLanguageDetector",
                "Model response contains inappropriate or offensive language. Substitution required.",
                Map.of(
                        "matchCount", matches.size(),
                        "safeFallback", SAFE_FALLBACK_RESPONSE
                )
        );
    }
}
