package com.google.adk.finance.v11.workflows;

import java.util.Map;
import java.util.Optional;

/**
 * Deterministic lifecycle interception contract for V11 sequential workflow stages.
 * <p>
 * Allows executing validation logic before a stage begins and observation/remediation
 * after a stage finishes.
 */
public interface WorkflowStageHook {

    /**
     * Executes immediately before a workflow stage runs.
     *
     * @param stageName identifier of the stage (e.g. "MARKET_RESEARCH")
     * @param stageContext read-only or mutable context dictionary passed to the stage
     * @return {@link Optional#empty()} if validation succeeds; or an error message if stage is blocked
     */
    Optional<String> beforeStage(String stageName, Map<String, Object> stageContext);

    /**
     * Executes immediately after a workflow stage completes.
     *
     * @param stageName identifier of the stage
     * @param stageContext context dictionary
     * @param stageOutput text output generated by the stage
     * @param durationMs execution time in milliseconds
     * @return {@link Optional#empty()} to leave output unchanged; or replacement/remediated output
     */
    Optional<String> afterStage(String stageName, Map<String, Object> stageContext, String stageOutput, long durationMs);
}
