package com.google.adk.finance.v11.hooks;

import com.google.adk.agents.CallbackContext;
import com.google.adk.agents.Callbacks.AfterModelCallbackSync;
import com.google.adk.models.LlmResponse;
import com.google.genai.types.Content;
import com.google.genai.types.Part;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Hook 3 — Response Validation Hook (BLOCKING / REMEDIATING).
 * <p>
 * Implements {@link AfterModelCallbackSync} to deterministically validate the generated response
 * against {@code v11/rules/response-rules.md} before delivering it to the end user:
 * <ol>
 *   <li><b>Non-Empty Enforcement:</b> Detects empty or blank model responses and applies fallback.</li>
 *   <li><b>Source Context Audit:</b> Verifies that if external data tools (MCP or Search) were invoked,
 *       proper source attribution or limitation context is included.</li>
 *   <li><b>Limitation Transparency:</b> If tools failed or were blocked, ensures operational limits are noted.</li>
 *   <li><b>Mandatory Disclaimer:</b> Enforces presence of the non-negotiable regulatory disclaimer.</li>
 * </ol>
 */
public class ResponseValidationHook implements AfterModelCallbackSync {
    private static final Logger logger = LoggerFactory.getLogger(ResponseValidationHook.class);

    public static final String HOOK_NAME = "ResponseValidationHook";

    public static final String MANDATORY_DISCLAIMER =
            "\n\n---\n> **Regulatory Notice & Disclaimer (v11)**: This analysis is generated by an autonomous AI system " +
                    "for educational and decision-support research purposes only. It does not constitute certified financial, " +
                    "legal, or investment advice. Always consult a licensed fiduciary before executing financial transactions.";

    private final HookRegistry hookRegistry;

    public ResponseValidationHook() {
        this(HookRegistry.getInstance());
    }

    public ResponseValidationHook(HookRegistry hookRegistry) {
        this.hookRegistry = Objects.requireNonNull(hookRegistry, "hookRegistry must not be null");
    }

    @Override
    public Optional<LlmResponse> call(CallbackContext callbackContext, LlmResponse llmResponse) {
        long startTime = System.currentTimeMillis();

        if (llmResponse.content().isEmpty()) {
            return Optional.empty();
        }

        Content content = llmResponse.content().get();

        // Critical: If the model generated a tool/function call, do NOT intercept or overwrite it.
        // Returning Optional.empty() allows Google ADK to dispatch the function call to the tool.
        if (containsFunctionCalls(content)) {
            logger.debug("[{}] Model response contains function call(s). Passing through for tool execution.", HOOK_NAME);
            return Optional.empty();
        }

        String originalText = extractText(content);
        if (originalText.isBlank()) {
            String fallback = "Error: Generated response was blank. " + MANDATORY_DISCLAIMER;
            recordExecution(false, true, "Blank response text detected", 0, startTime);
            return Optional.of(buildResponse(fallback));
        }

        String remediatedText = originalText;
        boolean wasModified = false;
        Map<String, Object> checks = new HashMap<>();

        // 1. Source Context Check: If MCP or Search was used, check for source mention
        boolean externalDataUsed = hookRegistry.wasMcpToolInvoked() || hookRegistry.wasSearchToolInvoked();
        checks.put("externalDataUsed", externalDataUsed);

        if (externalDataUsed) {
            boolean hasSourceMention = containsSourceAttribution(remediatedText);
            checks.put("hasSourceMention", hasSourceMention);
            if (!hasSourceMention) {
                logger.info("[{}] Response used external data but lacked explicit source attribution. Appending note.", HOOK_NAME);
                remediatedText += "\n\n> **Source Context (v11)**: Analysis grounded via Yahoo Finance MCP and/or Google Search tools.";
                wasModified = true;
            }
        }

        // 2. Limitation Check: If any tool was blocked or failed during this session
        if (hookRegistry.getBlockedCount() > 0) {
            boolean mentionsLimitations = containsLimitationMention(remediatedText);
            checks.put("mentionsLimitations", mentionsLimitations);
            if (!mentionsLimitations) {
                logger.info("[{}] Detected blocked operations in registry. Appending limitation disclosure.", HOOK_NAME);
                remediatedText += "\n\n> **Operational Limitations (v11)**: Certain queries were subject to source-rule validation or tool-access boundaries.";
                wasModified = true;
            }
        }

        // 3. Regulatory Disclaimer Check
        boolean hasDisclaimer = containsDisclaimer(remediatedText);
        checks.put("hasDisclaimer", hasDisclaimer);
        if (!hasDisclaimer) {
            logger.info("[{}] Enforcing mandatory regulatory disclaimer on final response.", HOOK_NAME);
            remediatedText += MANDATORY_DISCLAIMER;
            wasModified = true;
        }

        long duration = System.currentTimeMillis() - startTime;
        hookRegistry.recordHookExecution(HookResult.success(
                HOOK_NAME,
                HookPolicy.BLOCKING,
                wasModified ? "Response validated and remediated with compliance/source rules" : "Response passed all validation checks cleanly",
                checks,
                duration
        ));

        if (wasModified) {
            return Optional.of(buildResponse(remediatedText));
        }

        return Optional.empty(); // Keep original response
    }

    private boolean containsSourceAttribution(String text) {
        String lower = text.toLowerCase();
        return lower.contains("yahoo finance") ||
                lower.contains("google search") ||
                lower.contains("source:") ||
                lower.contains("sources:") ||
                lower.contains("sec filing") ||
                lower.contains("mcp");
    }

    private boolean containsLimitationMention(String text) {
        String lower = text.toLowerCase();
        return lower.contains("limitation") ||
                lower.contains("blocked") ||
                lower.contains("unavailable") ||
                lower.contains("gap") ||
                lower.contains("offline");
    }

    private boolean containsDisclaimer(String text) {
        String lower = text.toLowerCase();
        return lower.contains("regulatory notice") ||
                lower.contains("disclaimer") ||
                lower.contains("not constitute certified") ||
                lower.contains("licensed fiduciary");
    }

    private void recordExecution(boolean success, boolean blocked, String message, int textLength, long startTime) {
        long duration = System.currentTimeMillis() - startTime;
        hookRegistry.recordHookExecution(new HookResult(
                HOOK_NAME,
                HookPolicy.BLOCKING,
                success,
                blocked,
                message,
                Map.of("length", textLength),
                duration,
                java.time.Instant.now()
        ));
    }

    private LlmResponse buildResponse(String text) {
        Content content = Content.builder()
                .role("model")
                .parts(Part.fromText(text))
                .build();
        return LlmResponse.builder()
                .content(content)
                .build();
    }

    private String extractText(Content content) {
        if (content.parts().isEmpty()) {
            return "";
        }
        return content.parts().get().stream()
                .map(p -> p.text().orElse(""))
                .collect(Collectors.joining("\n"));
    }

    private boolean containsFunctionCalls(Content content) {
        if (content.parts().isEmpty()) {
            return false;
        }
        return content.parts().get().stream().anyMatch(p -> p.functionCall().isPresent());
    }
}
